// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsipxvnfhefetgnonjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c2lweHZuZmhlZmV0Z25vbmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTEzNjQsImV4cCI6MjA1MDk2NzM2NH0.zeFyaBuKExiZIgNzWh9sWE69-NUZc1LSgm_W1jT4ARQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);